version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  pgsql:
    domainname: pgsql
    image: postgres:alpine
    #            restart: always
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ali
      POSTGRES_PASSWORD: 123456
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - ./var/pgadmin-data:/var/lib/pgadmin
    links:
      - pgsql
